version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      JDBC_DRIVER_CLASS_NAME: org.postgresql.Driver
      JDBC_URL: jdbc:postgresql://db:5432/creditdb
      JDBC_USERNAME: yourusername
      JDBC_PASSWORD: yourpassword
      HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      HIBERNATE_SHOW_SQL: true
      HIBERNATE_HBM2DDL_AUTO: update

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: creditdb
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
